DROP TABLE IF EXISTS StorchenNest;
DROP TABLE IF EXISTS Sichtung;
DROP TABLE IF EXISTS Nest;
DROP TABLE IF EXISTS StorchFamilie;
DROP TABLE IF EXISTS Storch;
DROP TABLE IF EXISTS StorchenArt;
DROP TABLE IF EXISTS StorchenGattung;
